### PR TITLE
Fail Danger on linting errors. Closes #54

### LINKED ISSUE #54: Block PRs for rules with 'severity: error'
We currently use danger-swiftlint @ Slack to check for swift style issues, but we would love to be able to block PRs from being merged until these issues are properly fixed. Is there a way to do that currently with the plugin? If not, any workaround you'd think about? Thanks!

### PR DESCRIPTION
**Pull request by dzenbot**
Adding a new option, `fail_on_error` to fail Danger on linting errors only. I figured it would be best to make this opt-out, specially so it is backwards compatible with the behavior most users expect. Finally, with this option you'll ensure no one merges linting errors accidentally into `master` (cause, we can all be sloppy at times).

Closes https://github.com/ashfurrow/danger-swiftlint/issues/54

### CODE REVIEW

File: lib/danger_plugin.rb [hunk 1]
```diff
@@ -80,6 +80,11 @@ def lint_files(files=nil, inline_mode: false)
           message << markdown_issues(warnings, 'Warnings') unless warnings.empty?
           message << markdown_issues(errors, 'Errors') unless errors.empty?
           markdown message
+
+	  # Fail Danger on errors
+	  if fail_on_error && errors.count > 0
+	    fail
```
Comment (ashfurrow) [inline lib/danger_plugin.rb]: This could include a message like "Failed due to SwiftLint errors"

Comment (dzenbot) [reply lib/danger_plugin.rb]: Oh yeah, dough!

**Comment by ashfurrow** [comment]
Not a problem at all! I've pushed version 0.8.0 to RubyGems with this and a few other changes, so you should be able to use your change now. Let me know how it goes, and feel free to open issues for any other ideas!
